### ISSUE TITLE
please update deps

### ISSUE THREAD

**Issue by tomByrer** [yusukebe/url-shortener#4]
This repo breaks when I do

https://github.com/honojs/vite-plugins/issues/154

**Comment by yusukebe** [comment]
@tomByrer 

Already updated: https://github.com/yusukebe/url-shortener/commit/15dfba378c68e69252e7d252fe7c2ab6102e8fa8

**Comment by tomByrer** [comment]
I get this error on fresh reinstall & adding new URL:

```
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
TypeError: Cannot read properties of undefined (reading 'get')
    at createKey (/home/person/c/cf/url-shortener/src/index.tsx:99:27)
    at eval (/home/person/c/cf/url-shortener/src/index.tsx:109:21)
    at dispatch (file:///home/person/c/cf/url-shortener/node_modules/hono/dist/compose.js:29:23)
    at file:///home/person/c/cf/url-shortener/node_modules/hono/dist/compose.js:30:20
    at file:///home/person/c/cf/url-shortener/node_modules/hono/dist/validator/validator.js:78:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dispatch (file:///home/person/c/cf/url-shortener/node_modules/hono/dist/compose.js:29:17)
    at async cors (file:///home/person/c/cf/url-shortener/node_modules/hono/dist/middleware/csrf/index.js:30:5)
    at async dispatch (file:///home/person/c/cf/url-shortener/node_modules/hono/dist/compose.js:29:17)
    at async dispatch (file:///home/person/c/cf/url-shortener/node_modules/hono/dist/compose.js:29:17)
    ```

**Comment by yusukebe** [comment]
@tomByrer 

Create KV and add the setting to [`wrangler.toml`](https://github.com/yusukebe/url-shortener/blob/main/wrangler.toml):

https://github.com/yusukebe/url-shortener?tab=readme-ov-file#create-kv
